package com.example.withyou.ui.screens.login

val countryCodes = listOf(
    CountryCode("Afghanistan", "+93"),
    CountryCode("Albania", "+355"),
    CountryCode("Algeria", "+213"),
    CountryCode("Andorra", "+376"),
    CountryCode("Angola", "+244"),
    CountryCode("Argentina", "+54"),
    CountryCode("Armenia", "+374"),
    CountryCode("Australia", "+61"),
    CountryCode("Austria", "+43"),
    CountryCode("Azerbaijan", "+994"),
    CountryCode("Bahrain", "+973"),
    CountryCode("Bangladesh", "+880"),
    CountryCode("Belarus", "+375"),
    CountryCode("Belgium", "+32"),
    CountryCode("Brazil", "+55"),
    CountryCode("Brunei", "+673"),
    CountryCode("Bulgaria", "+359"),
    CountryCode("Cambodia", "+855"),
    CountryCode("Canada", "+1"),
    CountryCode("Chile", "+56"),
    CountryCode("China", "+86"),
    CountryCode("Colombia", "+57"),
    CountryCode("Croatia", "+385"),
    CountryCode("Cyprus", "+357"),
    CountryCode("Czech Republic", "+420"),
    CountryCode("Denmark", "+45"),
    CountryCode("Egypt", "+20"),
    CountryCode("Estonia", "+372"),
    CountryCode("Finland", "+358"),
    CountryCode("France", "+33"),
    CountryCode("Georgia", "+995"),
    CountryCode("Germany", "+49"),
    CountryCode("Ghana", "+233"),
    CountryCode("Greece", "+30"),
    CountryCode("Hong Kong", "+852"),
    CountryCode("Hungary", "+36"),
    CountryCode("Iceland", "+354"),
    CountryCode("India", "+91"),
    CountryCode("Indonesia", "+62"),
    CountryCode("Iran", "+98"),
    CountryCode("Iraq", "+964"),
    CountryCode("Ireland", "+353"),
    CountryCode("Israel", "+972"),
    CountryCode("Italy", "+39"),
    CountryCode("Japan", "+81"),
    CountryCode("Jordan", "+962"),
    CountryCode("Kazakhstan", "+7"),
    CountryCode("Kenya", "+254"),
    CountryCode("Kuwait", "+965"),
    CountryCode("Latvia", "+371"),
    CountryCode("Lebanon", "+961"),
    CountryCode("Libya", "+218"),
    CountryCode("Lithuania", "+370"),
    CountryCode("Luxembourg", "+352"),
    CountryCode("Malaysia", "+60"),
    CountryCode("Maldives", "+960"),
    CountryCode("Malta", "+356"),
    CountryCode("Mauritius", "+230"),
    CountryCode("Mexico", "+52"),
    CountryCode("Monaco", "+377"),
    CountryCode("Mongolia", "+976"),
    CountryCode("Montenegro", "+382"),
    CountryCode("Morocco", "+212"),
    CountryCode("Myanmar", "+95"),
    CountryCode("Nepal", "+977"),
    CountryCode("Netherlands", "+31"),
    CountryCode("New Zealand", "+64"),
    CountryCode("Nigeria", "+234"),
    CountryCode("North Korea", "+850"),
    CountryCode("Norway", "+47"),
    CountryCode("Oman", "+968"),
    CountryCode("Pakistan", "+92"),
    CountryCode("Palestine", "+970"),
    CountryCode("Panama", "+507"),
    CountryCode("Peru", "+51"),
    CountryCode("Philippines", "+63"),
    CountryCode("Poland", "+48"),
    CountryCode("Portugal", "+351"),
    CountryCode("Qatar", "+974"),
    CountryCode("Romania", "+40"),
    CountryCode("Russia", "+7"),
    CountryCode("Saudi Arabia", "+966"),
    CountryCode("Serbia", "+381"),
    CountryCode("Singapore", "+65"),
    CountryCode("Slovakia", "+421"),
    CountryCode("Slovenia", "+386"),
    CountryCode("South Africa", "+27"),
    CountryCode("South Korea", "+82"),
    CountryCode("Spain", "+34"),
    CountryCode("Sri Lanka", "+94"),
    CountryCode("Sudan", "+249"),
    CountryCode("Sweden", "+46"),
    CountryCode("Switzerland", "+41"),
    CountryCode("Syria", "+963"),
    CountryCode("Taiwan", "+886"),
    CountryCode("Tanzania", "+255"),
    CountryCode("Thailand", "+66"),
    CountryCode("Tunisia", "+216"),
    CountryCode("Turkey", "+90"),
    CountryCode("Ukraine", "+380"),
    CountryCode("United Arab Emirates", "+971"),
    CountryCode("United Kingdom", "+44"),
    CountryCode("United States", "+1"),
    CountryCode("Uruguay", "+598"),
    CountryCode("Uzbekistan", "+998"),
    CountryCode("Vatican City", "+39"),
    CountryCode("Venezuela", "+58"),
    CountryCode("Vietnam", "+84"),
    CountryCode("Yemen", "+967"),
    CountryCode("Zambia", "+260"),
    CountryCode("Zimbabwe", "+263")
)